### ISSUE TITLE
Small issues with the figures

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/tHMM#433]
1. In all figures, the cartoons don't have labels (a), (b), ...
2. In figure 2, the legend is not needed for (c) and (d), but I couldn't hide them for some reason.
3. In figure 2, the second-legends (o: G1, ^: G2)
4. Figure 1 is still left to do.
5. We could shade figure 5 vertically and partition it into three parts, corresponding to the cartoons.
6. 2 copies of the manuscript are being built in the manuscript.pdf.

**Comment by jclagarde** [comment]
<img width="980" alt="Screen Shot 2020-07-14 at 1 38 04 PM" src="https://user-images.githubusercontent.com/54101546/87474055-500ea900-c5d7-11ea-85e6-bfdef0ac8233.png">
figure 2 cartoon updated
