### ISSUE TITLE
Visualizing state assignment

### ISSUE THREAD

**Issue by shak360** [meyer-lab/tHMM#445]
We have some code to visualize our lineage trees. See the functions here: https://github.com/meyer-lab/tHMM/blob/master/lineage/plotTree.py and the way they are utilized in figure 7.

In the following paper, https://www.biorxiv.org/content/biorxiv/early/2018/12/07/488981.full.pdf, they have a figure where they visualize the state assignment output of their model.

![image](https://user-images.githubusercontent.com/20716101/87236260-cb841680-c39b-11ea-825d-42eb94db8a51.png)

It would be nice to add functionality to the plotting code to be able to do this. Recall that our model actually has two ways to assign states. The one we use a lot (most, if not all, of the time) is the Viterbi output, but an output that we don't really use is the state assignment from Baum Welch, encoded as `gammas`. The issue with using the `gammas` to do state assignment is that the assignments are partial (confidences that a cell belongs to a state). It would be interesting to look at the true states of the tree, the output from Baum Welch (`gammas`), and the output of Viterbi.

I'm imagining a 2 rows by 3 column figure, where the columns are 

1, the true states for a lineage, 
2, the Baum Welch output state assignment,
3, the Viterbi output

The first row being uncensored lineages, the second row being censored lineages.

**Comment by aarmey** [comment]
@Farnazmdi I think your code now does this? Close if so.

**Comment by Farnazmdi** [comment]
I tried using the output of Baum-Welch, but it was worst than Viterbi, so I didn't include it. Other than that, yes, the code has this.
