### ISSUE TITLE
7_14 to 7_28 to do list

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/tHMM#450]
A list to adjust the figures and the manuscript:

- [x] 1. Figure 1 (using figure 2 to build the two sets of population Dr. Meyer mentioned.)
1. A population where there is only one state and at the end, the cell number reaches ~ N
2. A population with two states where one state is almost quiescent and the other grows fast, so at the end, cell number reaches ~N. @jclagarde @shak360 

- [x] 2. Increasing cell number by depth + breadth in figure 3 @Farnazmdi 

- [x] 3. Increasing cell number in figure 3 to smooth the sharp edges of sd ribbon @shak360 
https://github.com/meyer-lab/tHMM/issues/454
- [x] 4. Rearranging figure 4 into 2 x 2 figures, in the top row there is the cartoon, and in the bottom, we have the accuracy and the distribution plot. @shak360 

- [x] 5. Rearranging figure 5 into 2 x 2 figures, in the top row there is the cartoon, and in the bottom, we have the accuracy. Also, the scaling problem of the cartoon (one tree is removed) @shak360 

- [ ] 6. Checking the accuracy @shak360 

- [x] 7. Edit the result subtitles. @Farnazmdi 

- [x] 8. Simulating the model with the raw data for control conditions, maybe doing AIC. @Farnazmdi 

- [x] 9. Writing some content for figure 3 (model performance). @Farnazmdi 
please write the caption for the figure accordingly.
- [x] 10. Writing some content for figure 4 (state distance). @Farnazmdi 
please write the caption for the figure accordingly.
- [x] 11. Writing some content for figure 5 (state representation). @shak360 
please write the caption for the figure accordingly.
- [x] 12. Writing some content for figure 6 (AIC). @lkargi @shak360 
please write the caption for the figure accordingly.

- [x] 13. Changing figure2 to the one explaining E step and M step. Dr. Meyer: "This figure should probably reflect the interface one uses to integrate different emissions. The two parts of this are the E and M steps... can we show this graphically?" @Farnazmdi 

- [ ] 14. Figure 4 has a slot for a cartoon. needs to be filled.

**Comment by Farnazmdi** [comment]
Let's take one or two tasks from this so we won't work on the same issue at a time. 
And please modify if I have forgotten something.

**Comment by shak360** [comment]
Wait sorry @Farnazmdi, is something happening on the 17th that requires this list to be completed?

**Comment by Farnazmdi** [comment]
sorry my bad! for some reason I thought today is 10th!!

**Comment by Farnazmdi** [comment]
Don't want to make this very long, so I close this and open another one.
