### ISSUE TITLE
Lowess smoothing on performance plots

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tHMM#454]
To reduce the jitter on the performance plots (comparing model output to true values over a range of models) we can use Lowess smoothing. This is reasonable because the model performance should be smooth w.r.t. these variables.

https://james-brennan.github.io/posts/lowess_conf/
https://www.statsmodels.org/stable/generated/statsmodels.nonparametric.smoothers_lowess.lowess.html

If you do this I would add back plotting the individual points so it's clear what is plotted (stochastic model results as opposed to some analytical solution). This removes the need to do binning and probably reduces the number of fits you need.

**Comment by Farnazmdi** [comment]
#468
