### ISSUE TITLE
Think of better way to throw out unusable lineages

### ISSUE THREAD

**Issue by shak360** [meyer-lab/tHMM#476]
Figure 3, amongst others, uses a while loop to pick and select lineages that are worth analyzing. For now, the conditions to be met are that the lineage must be heterogeneous and have more than a certain number of cells. 

Either this while loop code block that is frequently used (almost in every figure) has to be optimized or the lineage creation process has to be manipulated that lineages in general aren't poor candidates for analysis.

**Comment by lkargi** [comment]
Is the end-goal here to speed up the selection or do you want it to select even better lineages for analysis? It doesn't really seem like this is a bottleneck, in most figures this loop only runs once or twice each time.

**Comment by shak360** [comment]
If it's only running once or twice then that should be fine. A better place to start for this would be to profile figure 3 or at least figure out why figure 3 is taking a lot of time to run.

**Comment by Farnazmdi** [comment]
@lkargi Is this issue closed? I was a branch for this issue.
Figure3 is not taking that long though. I actually don't remember what the problem was. But profiling always helps. Did you get a chance to profile it?

**Comment by lkargi** [comment]
I kinda ended up working on this and 477 jointly, thats what the 476 branch is. The profile for fig3 is in issue 477.  I don't think you can gain much by just changing the while loop for all the figures, so I guess this can be closed, but I'm still working on 477 a bit.
