### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by shak360** [meyer-lab/tHMM#477]
Currently, figures take about 30 minutes to build, for 200 data points.

Profiling them to see which functions and which calls are taking up the most time can yield invaluable information on how to speed up the code. Speeding up the parts of the code that take up the most time (and sometimes memory access calls) can speed up the code. A speed of 3x or more is very noticeable and worthwhile.

See the messages here to learn how to do so:
https://github.com/meyer-lab/tHMM/issues/227#issuecomment-590603889

**Comment by lkargi** [comment]
![profile (1)](https://user-images.githubusercontent.com/61750387/89078171-79566580-d349-11ea-858e-7be3d98c161a.png)
@aarmey Here's the profile for figure 3.  Any advice on where we can optimize? Shakthi said the pdf call was a good candidate.

**Comment by aarmey** [comment]
That looks like the only clear possibility to me. Though, it's only ~20% of the time so it's not going to make everything 3X faster (~20% faster at best).

It's getting called a lot so turning most of it into a [numba](https://numba.pydata.org/numba-doc/latest/user/performance-tips.html) function can help. The *best* thing would be if the pdf could be called for all the cells at once in a vectorized fashion (i.e. you pass a matrix with all the observations, and get back all the probabilities). I'm not sure how feasible that is with how the emissions are stored right now.

**Comment by shak360** [comment]
```python
...
    for lineageObj in tHMMobj.X:  # for each lineage in our Population
        lineage = lineageObj.output_lineage  # getting the lineage in the Population by lineage index
        EL_array = np.zeros((len(lineage), tHMMobj.num_states))  # instantiating N by K array for each lineage

        for current_cell_idx, cell in enumerate(lineage):  # for each cell in the lineage
            for state_k in range(tHMMobj.num_states):  # for each state
                EL_array[current_cell_idx, state_k] = E[state_k].pdf(cell.obs)

        EL.append(EL_array)  # append the EL_array for each lineage
    return EL
```

`EL_array` is holding the probabilities.
`E` is a list of state distributions.

This is the function that utilizes the pdf. You can see the double `for` loop. I'm assuming we can at least vectorize the outer for loop over the cells, so the only for loop is over the states. The emissions are stored in the cells as a tuple. Do you think this can be vectorized @aarmey ?

**Comment by aarmey** [comment]
Yep. Just vectorizing the loop over cells would be a huge boost.
