### ISSUE TITLE
See how important seeding (initilization of states) is important to model performance

### ISSUE THREAD

**Issue by shak360** [meyer-lab/tHMM#478]
Some part of me thinks initialization should be handled better. Currently the variable `gammas` which represents the state representation is randomized. These can be thought of as "labels". I tried implementing a `KMeans` initialization solver, based on the observations. I don't have the code on `master` but I'll paste it here:

```python
            obsX = np.array([cell.obs for lineage in self.X for cell in lineage.output_lineage])
            # TODO: need to figure out a better way to init for censored data when considering nans
            # Replace nans with mean of the columns
            col_mean = np.nanmean(obsX, axis=0)
            # Find indices that you need to replace
            inds = np.where(np.isnan(obsX))
            # Place column means in the indices. Align the arrays using take
            obsX[inds] = np.take(col_mean, inds[1])
            kmeans_solver = KMeans(n_clusters=self.num_states).fit(obsX)
            init_gammas = [np.zeros((len(lineage), self.num_states)) for lineage in self.X]
            count = 0
            for _, lineage_gammas in enumerate(init_gammas):
                for _, cell_gamma in enumerate(lineage_gammas):
                    cell_gamma[kmeans_solver.labels_[count]] = 1
                    count += 1
```

This would ultimately go in step 0, of our tHMM `fit` function.

Ultimately, a relationship between how seeding is done, vs the accuracy and performance (how many steps untill iteration), could be shown.

**Comment by aarmey** [comment]
It'd be *really* hard to beat random initialization with a couple runs. Even KMeans has this as an initialization option.
