### ISSUE TITLE
nans in 3 or more state fitting in lineages with 1 cell.

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/tHMM#513]
For lineages with 1 or 3 cells, the AIC fails for more than 2 states, because gammas produce nans.

**Comment by Farnazmdi** [comment]
#521

**Comment by aarmey** [comment]
This might be fixed with #530?

**Comment by aarmey** [comment]
P.S. I don't think it's the AIC code—I think it happens in Baum-Welch (at least the failures I've seen).

**Comment by Farnazmdi** [comment]
I will write a test for 1-cell lineages. 


Thank you.
