### ISSUE TITLE
Lineages should be directly added to plots, not saved as SVG

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tHMM#524]
See information on how to do so here: https://stackoverflow.com/questions/17458580/embedding-small-plots-inside-subplots-in-matplotlib

**Comment by Farnazmdi** [comment]
I did it for figure 1, but I can't find a way to rotate the tree plots by 90 degrees like what we have right now. I had done it with the overlay_cartoon function. Any function I found that could rotate, needed an image. Would it be alright to keep the tree plots (cartoons) for figure 4 as it is right now? @aarmey
