### ISSUE TITLE
AIC code is still not right

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tHMM#531]
- [x] It shouldn't take the number of parameters as an option. It can figure this out from the tHMM object, and should check if any are fixed.
- [x] In both the real and synthetic data, the AIC should be a correction on the overall LL of the population, not individual lineages.
- [x] With the synthetic data figure, the whole process should run multiple times to generate multiple lines.
- [x] With the real data, we can add the AICs together across different concentrations of the drug to get one plot per drug.
- [x] There should be an AIC test. For example, maybe that the one state case gives one state as the answer more than half the time?

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/91670525-4d0e4000-ead3-11ea-8b35-39f68640f5e9.png)
I'm not sure we still need the histogram for real data with this setting. I mean showing a histogram for all cases at one graph may become confusing @aarmey.

**Comment by aarmey** [comment]
Agreed, we don't need the histogram. Rather than plot these separate lines, you can add these lines together to make one line.

**Comment by Farnazmdi** [comment]
I thought we consider different concentrations to be different cases. Could you please elaborate on what that line (the sum of the 4 concentrations) implies?

**Comment by Farnazmdi** [comment]
I got it. Maybe we consider treating each drug has a specific effect, regardless of its concentration?

**Comment by aarmey** [comment]
Fit each concentration and calculate its AIC separately. However, the AIC is a metric for the evidence supporting each case. If we assume there is a common number of states across concentrations, then we can add the lines together. That sum is the level of evidence for that number of states overall.

**Comment by Farnazmdi** [comment]
Thanks.

**Comment by aarmey** [comment]
Right. We're assuming the effect/mechanism of the drug is the same at every concentration.
