### ISSUE TITLE
Adjust figure tagging in manuscript

### ISSUE THREAD

**Issue by jclagarde** [meyer-lab/tHMM#560]

**Comment by jclagarde** [comment]
@aarmey I noticed that for some of the figure tagging in the manuscript results section, it uses brackets such as [@fig:wass] while some doesn't, such as @fig:prop. Is there a specific reason/system for using brackets or not using brackets?

**Comment by aarmey** [comment]
I thought the brackets were necessary but was apparently wrong. I think you want the version without brackets, because it looks like they show up in the final document.

**Comment by jclagarde** [comment]
@aarmey got it! thank you!

**Comment by Farnazmdi** [comment]
#561
