### ISSUE TITLE
remaining issue 9/24-9/31

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/tHMM#564]
- [x] plot lineage of different states for figure 9.

- [x] try different starting points.

- [x] Run profiling.

- [x] write more concise text in the manuscript with a focus on the big picture.

**Comment by aarmey** [comment]
I already looked through the profiling. What do you mean by different starting points? Like I've mentioned before, I don't think something like k-means initialization will be better. I think what we have is good.

**Comment by Farnazmdi** [comment]
I think we also talked about initialization for parameter estimation? Maybe I'm mistaken, I remember you said starting from different places in the plane may result differently because it is dependent on initial conditions. I believe we were looking at figure 5. I remember vaguely so it is likely that I'm wrong. @aarmey

**Comment by aarmey** [comment]
I think that's where I said we should run the fitting twice and take the better results. We do that now.

**Comment by Farnazmdi** [comment]
Oh yes, I will take that off the list.

**Comment by Farnazmdi** [comment]
One question @aarmey. Regarding the lineage plot for real data with their states as different colors in figure9, there are many lineages. Would it be alright if I plot like 3 or 4 of them as an example? (I actually don't see any other scenario, just wanted to make sure.)

**Comment by aarmey** [comment]
It'd be helpful to see as many as possible, but we can start with this.
