### ISSUE TITLE
the dimensions or gridsize in some supp figures are different from one another

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/tHMM#586]

**Comment by Farnazmdi** [comment]
@JC could you take a look at this?
![image](https://user-images.githubusercontent.com/34812750/92949588-2d9adf80-f410-11ea-8ab0-c546445e9d33.png)
![image](https://user-images.githubusercontent.com/34812750/92949619-3ab7ce80-f410-11ea-9439-6364f0ff815e.png)

Do you see the difference? The subfigure sizes don't seem to be the same. The font in the upper seems larger than the lower. Could you make sure they are structured in the same way?

**Comment by jclagarde** [comment]
@Farnazmdi I see what you mean. I will edit it them. Thanks for letting me know!

**Comment by Farnazmdi** [comment]
There were more figures with this discrepancy, I brought these two as an example. 
Thank you.
