### ISSUE TITLE
figure 10 is not in the main or supp figures yet

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/tHMM#588]
@aarmey Where would you want me to place figure 10 (lineage trees with their states colored)?
Also, should I add more lineages to it?

**Comment by aarmey** [comment]
Don't know yet. We should look at the fitted state emissions, too, before deciding this.

**Comment by aarmey** [comment]
The larger point is we need to understand and visually present where the different states are observed, and what is different about them. The figure does not yet do this.

**Comment by Farnazmdi** [comment]
Understood. Will the validating experiment go to this paper?

**Comment by aarmey** [comment]
Don't know yet. It probably depends in part what these results look like.
