### ISSUE TITLE
fig5 cartoon placement

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/tHMM#595]
![image](https://user-images.githubusercontent.com/34812750/93160598-82b34b80-f6c5-11ea-82a4-3c3b692d2389.png)
This is due to the change I made today. I am tagging you because you know the measures better than me.
I think you can replace the cartoon with the one that is used in the supplementary figures that has growing lineage in both depth and breadth and has time and fate censorship.

**Comment by jclagarde** [comment]
@Farnazmdi no problem! I will edit it!

**Comment by jclagarde** [comment]
@Farnazmdi Can I close this?

**Comment by Farnazmdi** [comment]
Sure.
