### ISSUE TITLE
Figure 4 edits

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tHMM#615]
- I think the spacing will work better if the plot is transposed so the lineages are placed vertically instead of horizontally with respect to each other. This will keep the plots from being flattened.
- The number of cells should extend down to a number where the performance isn't as good.

**Comment by aarmey** [comment]
The x-axis label on Fig. 5d is wrong.

**Comment by Farnazmdi** [comment]
I'm on it.

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/94075055-51b2d500-fdaf-11ea-8e87-012f84f1fccc.png)
If the lineages are rotated, I think it looks better. Is it alright if I do it? @aarmey

**Comment by Farnazmdi** [comment]
Oh actually, I can't. It was possible when these lineage trees were overlayed as cartoons.

**Comment by aarmey** [comment]
I think they look fine without rotation. The x-axis is time which fits with my intuition.

**Comment by jclagarde** [comment]
sorry, I had training for my job until now, so I just saw this! Was there anything else I could do to help resolve this issue?
