### ISSUE TITLE
setting a random seed to generate figures (mostly for figure4, but doesn't hurt to have for others, too)

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/tHMM#631]
I tried setting that inside the `cenGen()` and `regGen()` in figure 4, but didn't work. I tried placing it just on the top of `figureCommon`, didn't work either.

If I have to place it where the random values are being generated, maybe I should go inside `lineageTree`. @aarmey

**Comment by aarmey** [comment]
Try using this in genFigures.py:

https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.seed.html

https://github.com/meyer-lab/tHMM/blob/549a7ad724913e6048a6284f3555d49dbbb52db2/genFigures.py#L11
