### ISSUE TITLE
Fixed Random seed somewhere

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/tHMM#638]
I think we need to set a random seed somewhere. Because for example, the transition matrix (that I plot in a notebook now but we will merge to the figures lastly) should be consistent with the emission observations, but even now that I import the fitted lineages from figure 11, but still I think it will run that file again to get the fitted lineages out. Automatically they won't match without a random seed. 
We also wanted to find the lineage tree figure in figure4 constant.
 
Something I can think of instead of it is saving the transition matrix (and call for plotting T) and in the case of figure 4, I can plot one of the lineages from the data that I know shows censorship. @aarmey

**Comment by aarmey** [comment]
Then I think we need to build in the capacity to fit it in these specific places. Where are the random number generators that are causing this problematic variation?

**Comment by Farnazmdi** [comment]
For figure 4 is those two functions that generate the censored and uncensored lineages. 
and when we calculate the accuracy. 

I tried `np.random.seed()` in both figure files and in two runs got the same figure. I think it is good. I'll make a PR right now.
