### ISSUE TITLE
Figures S11, S12, S13 have inconsistent capitalization

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tHMM#791]
The axes and titles of these figures are not capitalized in the same format as other figures.

**Comment by aarmey** [comment]
Also, S15 doesn't need to have the color legend repeated. Just show in (a) and (e).

**Comment by aarmey** [comment]
@Farnazmdi have you checked this? Please close if so.

**Comment by Farnazmdi** [comment]
Was addressed in #808
